#!/usr/bin/env bash

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	termite
	# alacritty

# text editor
super + slash
	emacsclient --create-frame

# web browser
super + backslash
	firefox

# program launcher
super + @space
	rofi -modi drun -show drun # dmenu_run

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# Show clipmenu
super + v
	rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
#
# bspwm hotkeys
#

# quit bspwm normally
super + alt + Escape
	bspc quit

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,\~fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }n
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus given desktop
super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

# send to the given desktop and follow
super + shift + {1-9,0}
	bspc node -d '^{1-9,10}' --follow

# Move current window to a pre-selected space
super + shift + m
    bspc node -n last.!automatic

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
#super + ctrl + shift + space
#	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# resize windows i3 style
# use dash shell for its speed
super + ctrl + shift + {h,j,k,l}
    ;dash ~/.config/sxhkd/resize {x -, y +, y -, x +}

# contract a window by moving one of its side inward
#super + alt + shift + {h,j,k,l}
#	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Expand/contract a window by moving one of its side outward/inward
super + shift + r : {h,j,k,l}
    STEP=20; SELECTION={1,2,3,4}; \
    bspc node -z $(echo "left -$STEP 0,bottom 0 $STEP,top 0 -$STEP,right $STEP 0" | cut -d',' -f$SELECTION) || \
    bspc node -z $(echo "right -$STEP 0,top 0 $STEP,bottom 0 -$STEP,left $STEP 0" | cut -d',' -f$SELECTION)

# reset the layout of the current desktop
super + r
    bspc node @/ -E

#
# cmus/spotify audio keys
#

# pause/play
XF86AudioPlay
	cmus-remote -u || dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause

# next song
XF86AudioNext
	cmus-remote -n || dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

# previous song
XF86AudioPrev
	cmus-remote -r || dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous

# mute
XF86AudioMute
	amixer set Master toggle

#
# picom
#

# turn off
super + alt + x
	pkill picom

# turn on
super + alt + c
	picom --experimental-backends -b

#
# maim
#

# screenshot, copy to clipboard
super + Print
	maim -s | xclip -selection clipboard -t image/png

super + z
	maim -s | xclip -selection clipboard -t image/png


# screenshot, upload to imgur
super + shift + Print
	maim -su /tmp/screenshot.png; bash ~/Documents/Code/imgur-uploader/uploader.sh /tmp/screenshot.png | xclip -selection clipboard $argv;

super + shift + z
	maim -su /tmp/screenshot.png; bash ~/Documents/Code/imgur-uploader/uploader.sh /tmp/screenshot.png | xclip -selection clipboard $argv;

