#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	alacritty
	# termite

# text editor - emacs
super + slash
	emacsclient --create-frame

# web browser - firefox
super + backslash
	firefox-beta

# program launcher
super + @space
	rofi -modi drun -show drun # dmenu_run

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# show clipmenu
super + v
	rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'

# show a formatted list of sxhkd hotkeys in rofi with fuzzy searching
# TODO broken
super + F1
    ~/.config/sxhkd/show_help.sh

#
# bspwm hotkeys
#

# quit bspwm normally
super + alt + Escape
	bspc quit

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node on the current desktop
super + g
	bspc node -s biggest.local

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,\~fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
#super + {_,shift + }{h,j,k,l}
#	bspc node -{f,s} {west,south,north,east}

super + {h,j,k,l}
	bspc node -f {west,south,north,east}

super + shift + {h,j,k,l}
	~/.config/sxhkd/smart_move.sh {west,south,north,east}


# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }n
	bspc node -f {next,prev}.local

# focus the last node/desktop
alt + Tab
	bspc node -f last.local

alt + shift + Tab
	bspc desktop -f last

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus given desktop
super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

# select window to focus with rofi
# TODO broken
super + shift + @space
    ~/.config/sxhkd/select_node.sh

# send to the given desktop and follow
super + shift + {1-9,0}
	bspc node -d '^{1-9,10}' --follow

# Move current window to a pre-selected space
super + shift + m
    bspc node -n last.!automatic

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
#super + ctrl + shift + space
#	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# resize windows i3 style
# use dash shell for its speed
super + ctrl + shift + {h,j,k,l}
    ;dash ~/.config/sxhkd/resize {x -, y +, y -, x +}

# contract a window by moving one of its side inward
#super + alt + shift + {h,j,k,l}
#	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Expand/contract a window by moving one of its side outward/inward
# TODO - currently broken, see for reference: https://my-take-on.tech/2020/07/03/some-tricks-for-sxhkd-and-bspwm/
#super + shift + r : {h,j,k,l}
#    STEP=20; SELECTION={1,2,3,4}; \
#    bspc node -z $(echo "left -$STEP 0,bottom 0 $STEP,top 0 -$STEP,right $STEP 0" | cut -d',' -f$SELECTION) || \
#    bspc node -z $(echo "right -$STEP 0,top 0 $STEP,bottom 0 -$STEP,left $STEP 0" | cut -d',' -f$SELECTION)

# reset layout ratios of current desktop
super + r
    bspc node @/ -B

# reset the layout of the current desktop
super + shift + r
    bspc node @/ -E

#
# cmus/spotify audio keys
#

# pause/play
XF86AudioPlay
    playerctl play-pause
	#cmus-remote -u || dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause

# next song
XF86AudioNext
    playerctl next
	#cmus-remote -n || dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

# previous song
XF86AudioPrev
    playerctl previous
	#cmus-remote -r || dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous

# mute master volume
XF86AudioMute
	amixer set Master toggle

#
# picom
#

# turn off
super + alt + x
	pkill picom

# turn on
super + alt + c
	picom --experimental-backends -b

#
# dunst (notifications)
#

# close all notifications
super + F2
	dunstctl close-all

# show notification history
super + F3
	dunstctl history-pop


#
# maim
#

# screenshot, upload to imgur
#super + Print
#	maim -su /tmp/screenshot.png; bash ~/Documents/Code/imgur-uploader/uploader.sh /tmp/screenshot.png | xclip -selection clipboard $argv;

#super + z
#	maim -su /tmp/screenshot.png; bash ~/Documents/Code/imgur-uploader/uploader.sh /tmp/screenshot.png | xclip -selection clipboard $argv;

# screenshot, copy to clipboard
super + Print
    maim -s --format png /dev/stdout | xclip -selection clipboard -t image/png -i
	#maim -s | xclip -selection clipboard -t image/png

super + ctrl + Print
    maim -s --format png ~/Downloads/temp.png

super + z
    maim -s --format png /dev/stdout | xclip -selection clipboard -t image/png -i
	#maim -s | xclip -selection clipboard -t image/png

