#! /bin/sh

bspc monitor DP-2 -d I II III IV V VI VII
bspc monitor DP-0 -d VIII IX X

# swallow - not used currently
# pidof bspswallow || bspswallow & #

# randomly select a wallpaper
#wallpaper=$(ls ~/Wallpapers/Landscapes/* | shuf --random-source=/dev/urandom -n 1)
wallpaper="/home/zac/Documents/Google/Wallpapers/wallhaven-n6xdv6.jpg"

## PYWAL
#wal -i $wallpaper -n
#source ~/.cache/wal/colors.sh

# set randomized wallpaper from start of config with feh
feh --bg-fill $wallpaper

## bspc configs
# pywal border colors
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

# nord border colors
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#eceff4"
bspc config focused_border_color "#88c0d0"
bspc config presel_feedback_color "#88c0d0"

# dracula border colors
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"


# faster refresh rate for moving floating windows
bspc config pointer_motion_interval 7ms

# padding for bar
bspc config -m DP-2 top_padding 30

# borderless gaps, standard split ratio
bspc config border_width         5
bspc config window_gap           15
bspc config split_ratio          0.5

# gaps in monocle mode
bspc config borderless_monocle   true
bspc config gapless_monocle      false

## bspc rules
# force these programs to start on a specific desktop
#bspc rule -a Steam desktop='^2' follow=off
#bspc rule -a discord desktop='^10'

#bspc rule -a Slack desktop='^10'
# this one is broken https://github.com/baskerville/bspwm/issues/291
#bspc rule -a Spotify desktop='^10'

# force tiling/floating
#bspc rule -a Gimp state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Zathura state=tiled
#bspc rule -a yad state=floating
bspc rule -a Emacs state=tiled
bspc rule -a matplotlib state=floating

## env vars
# NOTE this must be done before starting background procs
export SXHKD_SHELL=/usr/bin/dash # perf optimization
export _JAVA_AWT_WM_NONREPARENTING=1 # matlab hack
export GTK_THEME=Dracula # gtk 4 theming

## autostart
# fix cursor turning into an x on the desktop
# https://wiki.archlinux.org/title/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr

# hotkey manager
sxhkd &

# display warmer
redshift &

# clipboard manager
clipcatd

# notification manager
dunst &

# compositor
#picom --experimental-backends -b
picom &

# autostart jack
#jack_control start

# bar(s)
~/.config/polybar/launch.sh
#tint2 &
# tint2 correct behaviour for overlapping windows
# NOTE this seems to fail once windows sleep
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)


wmname LG3D # hack java programs to work

