#! /bin/sh

sxhkd &

bspc monitor DP-4 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Yad state=floating
bspc rule -a Steam desktop='^3' follow=off
bspc rule -a discord desktop='^4'
bspc rule -a Deluge desktop='^5'
bspc rule -a Zathura state=tiled

# wallpaper with feh
feh --randomize --bg-fill ~/Wallpapers/Landscapes/*

# autostart stuff 
redshift &
dunst &
compton -b
~/.config/polybar/launch.sh
