#! /bin/sh

sxhkd &


wallpaper=$(ls ~/Wallpapers/Landscapes/* | shuf -n 1)
wal -i $wallpaper -n

source ~/.cache/wal/colors.sh

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor HDMI-0 -d I
bspc monitor DP-2 -d II
bspc monitor DP-4 -d II IV V VI VII VIII IX
bspc monitor DP-0 -d X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^4' follow=off
bspc rule -a discord desktop='^10'
bspc rule -a Deluge-gtk desktop='^1'
bspc rule -a Transmission-gtk desktop='^1'
bspc rule -a Zathura state=tiled
bspc rule -a yad state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Code desktop='^5'

# wallpaper with feh
#feh --randomize --bg-fill ~/Wallpapers/Landscapes/*
feh --bg-fil $wallpaper

wal_steam -w -d

# autostart stuff 
redshift &
dunst &
compton -b
~/.config/polybar/launch.sh
